In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib as plt
%matplot inline

In [7]:
df = pd.read_csv("hiring.csv")

In [8]:
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5595 sha256=735ff1a106b9009f9b237c7852abf4e56d7fc264c5b6d22be1aaeb7990094a24
  Stored in directory: c:\users\pvine\appdata\local\pip\cache\wheels\4b\c3\77\a5f48aeb0d3efb7cd5ad61cbd3da30bbf9ffc9662b07c9f879
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [10]:
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [11]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
from word2number import w2n
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [25]:
df.experience = df.experience.apply(w2n.word_to_num)

In [30]:
import math
median_ts = math.floor(df["test_score(out of 10)"].median())

In [31]:
median_ts


8

In [33]:
df["test_score(out of 10)"]= df["test_score(out of 10)"].fillna(median_ts)

In [34]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [38]:
reg = linear_model.LinearRegression()
reg.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [39]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [40]:
reg.intercept_


17737.26346433768

In [43]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [44]:
reg.predict([[12,10,10]])

array([92002.18340611])